# This is a workflow to automate the dataset creation of wastewater data for Ottawa.

name: Ottawa-Dataset-creation

# Runs everyday at 12:30pm EST/EDT (4:00pm UTC)
on:
  schedule:
    - cron: '0 16 30 * *'
  workflow_dispatch:
  
jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Download Ottawa wastewater data
        uses: wei/curl@v1.1.1
        with:
          args: |
            -H \'Token: ${{ secrets.PAT_TOKEN }}'\ -L https://raw.githubusercontent.com/Big-Life-Lab/COWS-private/main/Ottawa/Data/wastewater_virus.csv --output Ottawa/Data/wastewater_virus.csv --create-dirs -L https://raw.githubusercontent.com/Big-Life-Lab/COWS-private/main/Ottawa/Data/wwMeasure.csv --output Ottawa/Data/wwMeasure.csv --create-dirs
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update Ottawa data" -a || echo "Nothing to update"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: 'cows-private-connect'
